20240305【Ruby】lsコマンドを作る
taichihub/ruby-practices pull request #4
Opened 2024-03-05 03:41 UTC by taichihub

2024-03-10 02:55 UTC, u1tnk commented
まず、今までの全てのプラクティスの内容が このＰＲに入っているようなので、 このプラクティスの内容だけにしてください。

2024-03-10 03:01 UTC, u1tnk requested changes
まず、今までの全てのプラクティスの内容が このＰＲに入っているようなので、 このプラクティスの内容だけにしてください。

また file1などはテスト用だと思うのですが、その場合は以下二点は必要です。
- テスト用のデータファイルは分かりやすいようにディレクトリなどにまとめておく
- テスト用のデータファイルを置くのであればそれを使ったテストコードも合わせてコミットする

テストコードはこのプラクティスでは必須では無いので、難しい場合はコミットしないようにしてください。

`male_ls_command.rb` とありますが mainのスペルミスでしょうか？
スペルミスは気をつけてもらうとして、 lsディレクトリにあるので main.rbとか ls.rb とかもうちょっとシンプルなもので大丈夫です。


まだ細かいロジックは見ていません。
PRを作ったら一通り自分で見てみて、セルフレビューするようにすると良いと思います 💪

2024-03-19 07:23 UTC, taichihub commented
@u1tnk 

> まず、今までの全てのプラクティスの内容が このＰＲに入っているようなので、 このプラクティスの内容だけにしてください。

向いてるブランチを修正しました。

> また file1などはテスト用だと思うのですが、その場合は以下二点は必要です。
テスト用のデータファイルは分かりやすいようにディレクトリなどにまとめておく
テスト用のデータファイルを置くのであればそれを使ったテストコードも合わせてコミットする

かしこまりました🙇‍♂️

> male_ls_command.rb とありますが mainのスペルミスでしょうか？
スペルミスは気をつけてもらうとして、 lsディレクトリにあるので main.rbとか ls.rb とかもうちょっとシンプルなもので大丈夫です。

`make`のスペルミスでした。ls.rbに変更しておきます。

> まだ細かいロジックは見ていません。
PRを作ったら一通り自分で見てみて、セルフレビューするようにすると良いと思います 💪

細かいロジックの前にPR提出時にPRの体裁として正常なものかを見るようにします

2024-03-19 15:18 UTC, u1tnk reviewed
lsのプログラム部分見てコメントしました！
全体の処理は良さそうですが、細かいところが多いです。
細かいと思われそうですが、業務では変数名なども大事です。

> また file1などはテスト用だと思うのですが、その場合は以下二点は必要です。
テスト用のデータファイルは分かりやすいようにディレクトリなどにまとめておく
テスト用のデータファイルを置くのであればそれを使ったテストコードも合わせてコミットする
かしこまりました🙇‍♂️

この部分ですが、対応されてないように見えます「対応した」とも書いてないのでコメント返してから対応する予定だったのかもしれませんが、ちょっと読み取れなかったのではっきり書いて欲しかったです。

あとは悪いわけでは無いですが「分かりました」ぐらいで大丈夫ですよ 🙆‍♀️

2024-03-19 15:18 UTC, u1tnk commented on 04.ls/ls.rb
> +class Array
既存のクラスを修正できるのはrubyの良いところですが、影響範囲が大きくなるので業務ではよほど必要なケース以外では使用しません。
なので使用しないようにして実装してください。

2024-03-19 15:18 UTC, u1tnk commented on 04.ls/ls.rb
> +def natural_sort(files)
こちらの方が自然に感じるのはもっともだと思うのですが、基本的にlsコマンドに似せるプラクティスです。厳密に合わせる必要は無いですが、なるべく合わせるようにしましょう。

2024-03-19 15:18 UTC, u1tnk commented on 04.ls/ls.rb
> +def calculate_items_per_column(total_items)
列ごとの配列の処理と思うのですが、 変数名の`total_` の必要性が無さそうに思います。

2024-03-19 15:18 UTC, u1tnk commented on 04.ls/ls.rb
> +SPACES = 8
SPACESだと空白の数のように見えるのでもう少し用途が分かる名前にしましょう。

2024-03-19 15:19 UTC, u1tnk requested changes
間違って Request Changesじゃなくて Commentにしてしまったので再コメント 🙏 気にしないでください。

2024-03-23 07:04 UTC, taichihub commented on 04.ls/ls.rb
> +def calculate_items_per_column(total_items)
@u1tnk 
`total_items`を`items`に修正することで対応しました

2024-03-23 07:06 UTC, taichihub commented on 04.ls/ls.rb
> +SPACES = 8
@u1tnk 
`BLANK_SIZE`に変更しました

2024-03-23 07:10 UTC, taichihub commented on 04.ls/ls.rb
> +class Array
@u1tnk 
Arrayクラスを修正するのではなく独立したsafe_transposeメソッドを作成しました

2024-03-23 07:38 UTC, taichihub commented on 04.ls/ls.rb
> +def natural_sort(files)
@u1tnk 
自然順ではなく辞書型に修正しました

2024-03-23 07:39 UTC, taichihub commented
@u1tnk 
こちら修正完了しましたので確認よろしくお願いします！

2024-03-24 16:10 UTC, u1tnk approved these changes

2024-09-05 08:02 UTC, merged