20240422【Ruby】lsコマンドを作る4
taichihub/ruby-practices pull request #7
Opened 2024-04-22 04:35 UTC by taichihub

2024-04-22 14:56 UTC, u1tnk requested changes

2024-04-22 14:56 UTC, u1tnk commented on 04.ls/ls.rb
> +def file_details(entry)
fileの詳細情報を出力するフォーマットで取得するメソッド
に見えるのでファイル名はウソでは無いですが、適切では無いと思います。

2024-04-22 14:56 UTC, u1tnk commented on 04.ls/ls.rb
> +  long_list = ARGV.include?('-l')
_list となると変数名は何かの配列が入っているんじゃないかと思ってしまうので(ruby界隈だと_list,_arrayは使わずに複数形を使うことが多いですが)変数名を検討してください。

2024-04-22 14:56 UTC, u1tnk commented on 04.ls/ls.rb
> +def long_listing(entries)
このメソッド名も-lオプションのときの何かをしていることしか分からないので検討ください。

2024-04-23 11:02 UTC, taichihub commented on 04.ls/ls.rb
> +def file_details(entry)
@u1tnk 
`get_file_details`に変更することで対応しました。

2024-04-23 11:07 UTC, taichihub commented on 04.ls/ls.rb
> +  long_list = ARGV.include?('-l')
@u1tnk 
`detail_order`に変更することで対応しました

2024-04-23 11:10 UTC, taichihub commented on 04.ls/ls.rb
> +def long_listing(entries)
@u1tnk 
`get_file_detail`に変更することで対応しました

2024-04-23 14:43 UTC, u1tnk commented on 04.ls/ls.rb
> +def file_details(entry)
get_の部分は重要ではなく、 file_detailsではることはウソでは無いが、適切では無いという指摘です。

2024-04-23 14:44 UTC, u1tnk commented on 04.ls/ls.rb
> +  long_list = ARGV.include?('-l')
その直前の reverse_orderの orderは順番という意味と思いますが、detail_orderで意図した意味になっているでしょうか？

2024-04-24 04:13 UTC, taichihub commented on 04.ls/ls.rb
> +  long_list = ARGV.include?('-l')
@u1tnk 
`order`は「注文する」の意味合いでしようしています。なので、
・`reserve_order`は「逆並びの注文」のような意味合い
・`detail_order`は「詳細情報の注文」のような意味合い
でしようしています。

2024-04-24 04:44 UTC, taichihub commented on 04.ls/ls.rb
> +def file_details(entry)
@u1tnk 
「fileの詳細情報を『出力する』フォーマットで取得するメソッド」なので、`get_file_details`ではなく`output_file_details`に変更しました。

2024-04-26 13:32 UTC, u1tnk commented on 04.ls/ls.rb
> +  long_list = ARGV.include?('-l')
意図は理解できましたが
-「注文」の意味では抽象度が高過ぎて意図が読みづらい
- そうなると `-a` がorderじゃないのがなぜ？と思ってしまう。

シンプルにもうちょっと意図が分かりやすい名前があると思うのでもう少し考えてみてください 🙏

2024-04-26 14:16 UTC, u1tnk commented on 04.ls/ls.rb
> +def file_details(entry)
output用ということだと思いますが、メソッド名は動詞と名詞なら 「動詞_目的語」となるので、この名前だと出力までするように見えます。
冗長になっても良いのでもう少し詳細度を上げましょう。

2024-05-01 05:50 UTC, taichihub commented on 04.ls/ls.rb
> +def file_details(entry)
@u1tnk 
ファイルのメタデータをフォーマット化するという用途なのでこのような命名にしました。
`format_file_metadata_as_string`

2024-05-01 06:02 UTC, taichihub commented on 04.ls/ls.rb
> +  long_list = ARGV.include?('-l')
@u1tnk 
単純にファイルの詳細情報を表示するものということで以下のように変更しました
`display_detailed_file_information`

2024-05-01 07:59 UTC, u1tnk requested changes

2024-05-01 07:59 UTC, u1tnk commented on 04.ls/ls.rb
> +def format_file_metadata_as_string(entry)
formatが一般的に整形した文字列という意味があるので `as_string`  は必要無いです。
また、metadataも悪くは無いのですが、直下の get_file_detailと名前の整合性が取れていないです。
get_file_detailが単数のように見えることもあるのでを合わせてformat_xxxで複数形、単数形で分けると良いかと思います。

2024-05-01 07:59 UTC, u1tnk commented on 04.ls/ls.rb
> +  entries.map { |entry| format_file_metadata_as_string(entry) }
だいぶ細かいので修正しなくても良いですが一応指摘すると putsで配列をそのまま出力すると改行されて出力される仕様に依存しているので、改行コードを入れた文字列として返すとより良いかなと思いました。

2024-05-01 07:59 UTC, u1tnk commented on 04.ls/ls.rb
> +    detailed_entries = get_file_detail(sorted_entries)
detailedというのもおかしいですし、 format_xxxの戻り値になると思うので formattedの方が良さそうですね。

2024-05-02 05:04 UTC, taichihub commented on 04.ls/ls.rb
> +def format_file_metadata_as_string(entry)
@u1tnk 
`format_file_metadata_as_string`を`format_files_detail`に変更しました。
→複数ファイルの詳細情報をフォーマットするから。
`get_file_detail`を`format_file_detail`に変更しました。
→複数形と単数系で分けた。

2024-05-02 05:05 UTC, taichihub commented on 04.ls/ls.rb
> +    detailed_entries = get_file_detail(sorted_entries)
@u1tnk 
`formatted_entries`に変更しました。

2024-05-02 15:09 UTC, u1tnk commented on 04.ls/ls.rb
> +def format_file_metadata_as_string(entry)
ちょっと認識が違います。

`format_files_detail ` の方は複数回呼ばれるとは思いますが、このメソッド自体は一つのファイルを処理するんじゃないでしょうか？
また、 files_detailはあまり見ないので file_details の方が良いと思います。基本的には複合しているときは後ろが複数形の方が見やすいですし。

format_file_detail の方は 配列をもらっていて、 上の一つのファイルを処理するものを複数回呼んで処理するので複数形を期待していました。

2024-05-03 05:53 UTC, taichihub commented on 04.ls/ls.rb
> +def format_file_metadata_as_string(entry)
@u1tnk 
`format_file_detail`
1つ1つファイルの詳細情報(メタデータ)をフォーマット通りに整形し出力
`format_file_details`
そのディレクトリに入っている複数のファイルを1つずつ整形作業をさせるためにformat_file_detailに渡す

2024-05-04 15:35 UTC, u1tnk approved these changes

2024-09-05 08:03 UTC, merged