lsコマンドを作る5
taichihub/ruby-practices pull request #8
Opened 2024-05-08 08:21 UTC by taichihub

2024-05-08 15:49 UTC, u1tnk requested changes
optionsの処理をまとめるなどは本来の ls5の目的では無いので、PRのdescription(説明のところ)にでも何をしたのか書いてもらえると分かりやすかったかなと思います。
プラクティスであんまりこだわらないようにしていますが、PRのdescriptionは業務では空などはありえないので何をやったかの概要ぐらいは書いてもらう方が良いと思います。

2024-05-08 15:49 UTC, u1tnk commented on 04.ls/ls.rb
> +  if options[:detailed_info]
optionsにまとめたのは引数のオプションであることが分かりやすくなったので良いと思います 👍 
なのですが、display_detailed_file_information は ls4のレビューであれだけ議論した名前なのになぜ変えたんでしょうか？

display_detailed_file_information がシンプルで良い名前では無いですが、一応合格レベルの名前でした。
'detailed_info'だと infoは抽象的過ぎてほぼ情報量が無いので日本語にすると「詳細」としか言っていません。
「詳細を表示する」情報は含んで欲しいです。

また、 infoは使わない方が良いなどを含めた僕のFBC生向けのブログ記事があるので目を通してもらえると参考になると思います。 https://u1tnk.github.io/blog/2022/12/04/naming_variable/

2024-05-10 05:09 UTC, taichihub commented on 04.ls/ls.rb
> +  if options[:detailed_info]
@u1tnk 
すみません、実装中に無意識的に`detailed_info`に戻してしまっていました。
`detailed_info`を`display_detailed_file_information`に戻しておきました。

2024-05-10 05:10 UTC, taichihub commented
@u1tnk 
> プラクティスであんまりこだわらないようにしていますが、PRのdescriptionは業務では空などはありえないので何をやったかの概要ぐらいは書いてもらう方が良いと思います。

こちらについては、fjordの提出物に記述するところがPRのdexcriptionにあたるものだと思っていたので書いていなかったです🙇‍♂️
普段の開発ではテンプレートを入れています。

2024-05-10 08:37 UTC, u1tnk approved these changes

2024-09-05 08:03 UTC, merged